before_install:
  - sudo apt-get install -y libudev-dev
language: rust
rust:
  # If the MSRV is updated, update the readme
  - 1.65.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add rustfmt-preview
  - which rustfmt
env:
  - FEATURES="--no-default-features --features std"
  - FEATURES="--no-default-features --features alloc"
  - FEATURES="--no-default-features"
script:
  - cd ublox_derive
  - cargo test --verbose --workspace
  - cd ../ublox
  - cargo test $FEATURES
  - cargo build $FEATURES --examples
  - cargo doc $FEATURES
