#![cfg(feature = "ubx_proto23")]

#[cfg(feature = "serde")]
use super::{SerializeMap, SerializeUbxPacketFields};

use crate::ubx_packets::packets::{
    ack::{AckAck, AckAckOwned, AckAckRef, AckNak, AckNakOwned, AckNakRef},
    cfg_ant::CfgAnt,
    cfg_esf_alg::CfgEsfAlg,
    cfg_esf_wt::CfgEsfWt,
    cfg_gnss::CfgGnss,
    cfg_inf::CfgInf,
    cfg_itfm::CfgItfm,
    cfg_nav5::CfgNav5,
    cfg_odo::CfgOdo,
    cfg_prt::{CfgPrtI2c, CfgPrtSpi, CfgPrtUart},
    cfg_tmode2::CfgTmode2,
    cfg_tmode3::CfgTmode3,
    cfg_tp5::CfgTp5,
    esf_alg::EsfAlg,
    esf_ins::EsfIns,
    esf_meas::EsfMeas,
    esf_raw::EsfRaw,
    esf_status::EsfStatus,
    hnr_att::HnrAtt,
    hnr_ins::HnrIns,
    hnr_pvt::HnrPvt,
    inf_debug::InfDebug,
    inf_error::InfError,
    inf_notice::InfNotice,
    inf_test::InfTest,
    inf_warning::InfWarning,
    mga_ack::MgaAck,
    mga_bds_eph::MgaBdsEph,
    mga_bds_utc::MgaBdsUtc,
    mga_gal_eph::MgaGalEph,
    mga_gal_time::MgaGalTime,
    mga_glo_eph::MgaGloEph,
    mga_gps_eph::MgaGpsEph,
    mga_gps_iono::MgaGpsIono,
    mga_gps_utc::MgaGpsUtc,
    mon_gnss::MonGnss,
    mon_hw::MonHw,
    mon_hw2::{MonHw2, MonHw2Owned, MonHw2Ref},
    mon_io::{MonIo, MonIoOwned, MonIoRef},
    mon_msgpp::MonMsgpp,
    mon_patch::MonPatch,
    mon_rxbuf::MonRxbuf,
    mon_rxr::MonRxr,
    mon_txbuf::MonTxbuf,
    mon_ver::MonVer,
    nav_att::NavAtt,
    nav_clock::NavClock,
    nav_dop::NavDop,
    nav_hp_pos_ecef::NavHpPosEcef,
    nav_hp_pos_llh::NavHpPosLlh,
    nav_other::{NavEoe, NavOdo, NavVelECEF},
    nav_pos_llh::NavPosLlh,
    nav_pvt::proto23::NavPvt,
    nav_rel_pos_ned::proto23::NavRelPosNed,
    nav_sat::NavSat,
    nav_sol::NavSol,
    nav_status::NavStatus,
    nav_time_ls::NavTimeLs,
    nav_time_utc::NavTimeUTC,
    nav_vel_ned::NavVelNed,
    rxm_rawx::RxmRawx,
    rxm_rtcm::RxmRtcm,
    rxm_sfrbx::RxmSfrbx,
    sec_uniq_id::SecUniqId,
    tim_svin::TimSvin,
    tim_tm2::TimTm2,
    tim_tos::TimTos,
    tim_tp::TimTp,
};
use crate::{ParserError, UbxPacketMeta, UbxUnknownPacket};
use ublox_derive::define_recv_packets;

define_recv_packets!(
    enum Packet {
        _ = UbxUnknownPacket<MAX_PAYLOAD_LEN>,
        AckAck,
        AckNak,
        CfgAnt,
        CfgEsfAlg,
        CfgEsfWt,
        CfgGnss,
        CfgInf,
        CfgItfm,
        CfgNav5,
        CfgOdo,
        CfgPrtI2c,
        CfgPrtSpi,
        CfgPrtUart,
        CfgSmgr,
        CfgTmode2,
        CfgTmode3,
        CfgTp5,
        EsfAlg,
        EsfIns,
        EsfMeas,
        EsfStatus,
        EsfRaw,
        InfError,
        InfWarning,
        InfNotice,
        InfTest,
        InfDebug,
        HnrAtt,
        HnrIns,
        HnrPvt,
        MonVer,
        MonGnss,
        MonHw,
        MonHw2,
        MonIo,
        MonPatch,
        MonMsgpp,
        MonRxr,
        MonRxbuf,
        MonTxbuf,
        MgaAck,
        MgaGpsIono,
        MgaGpsEph,
        MgaGpsUtc,
        MgaBdsEph,
        MgaBdsUtc,
        MgaGalEph,
        MgaGalTime,
        MgaGloEph,
        NavAtt,
        NavClock,
        NavDop,
        NavEoe,
        NavHpPosLlh,
        NavHpPosEcef,
        NavOdo,
        NavPvt,
        NavPosLlh,
        NavRelPosNed,
        NavSat,
        NavSol,
        NavStatus,
        NavVelNed,
        NavTimeUTC,
        NavTimeLs,
        NavVelECEF,
        RxmRawx,
        RxmRtcm,
        RxmSfrbx,
        SecUniqId,
        TimSvin,
        TimTp,
        TimTm2,
        TimTos,
    }
);
