#![cfg(feature = "ubx_proto14")]

use super::*;
use crate::{ParserError, UbxPacketMeta, UbxUnknownPacketOwned, UbxUnknownPacketRef};
use ublox_derive::define_recv_packets;

define_recv_packets!(
    enum Packet {
        _ = UbxUnknownPacket,
        AlpSrv,
        AckAck,
        AckNak,
        CfgAnt,
        CfgItfm,
        CfgNav5,
        CfgOdo,
        CfgPrtI2c,
        CfgPrtSpi,
        CfgPrtUart,
        CfgSmgr,
        CfgTmode2,
        CfgTmode3,
        CfgTp5,
        EsfRaw,
        InfError,
        InfWarning,
        InfNotice,
        InfTest,
        InfDebug,
        MonVer,
        MonGnss,
        MonHw,
        MgaAck,
        MgaGpsIono,
        MgaGpsEph,
        MgaGloEph,
        NavAtt,
        NavClock,
        NavDop,
        NavEoe,
        NavHpPosLlh,
        NavHpPosEcef,
        NavOdo,
        NavPvt,
        NavPosLlh,
        NavRelPosNed,
        NavSat,
        NavSol,
        NavStatus,
        NavVelNed,
        NavTimeUTC,
        NavTimeLs,
        NavVelECEF,
        RxmRawx,
        RxmRtcm,
        RxmSfrbx,
        SecUniqId,
        TimSvin,
        TimTp,
        TimTm2,
        TimTos,
    }
);
