#![cfg(feature = "ubx_proto27")]

#[cfg(feature = "serde")]
use {super::SerializeUbxPacketFields, crate::serde::ser::SerializeMap};

use crate::ubx_packets::packets::{
    ack::{AckAck, AckNak},
    cfg_ant::CfgAnt,
    cfg_esf_alg::CfgEsfAlg,
    cfg_esf_wt::CfgEsfWt,
    cfg_gnss::CfgGnss,
    cfg_inf::CfgInf,
    cfg_itfm::CfgItfm,
    cfg_nav5::CfgNav5,
    cfg_odo::CfgOdo,
    cfg_prt::{CfgPrtI2c, CfgPrtSpi, CfgPrtUart},
    cfg_tmode2::CfgTmode2,
    cfg_tmode3::CfgTmode3,
    cfg_tp5::CfgTp5,
    cfg_val::CfgValGetResponse,
    esf_alg::EsfAlg,
    esf_ins::EsfIns,
    esf_meas::EsfMeas,
    esf_raw::EsfRaw,
    esf_status::EsfStatus,
    inf_debug::InfDebug,
    inf_error::InfError,
    inf_notice::InfNotice,
    inf_test::InfTest,
    inf_warning::InfWarning,
    mga_ack::MgaAck,
    mga_bds_eph::MgaBdsEph,
    mga_bds_utc::MgaBdsUtc,
    mga_gal_eph::MgaGalEph,
    mga_gal_time::MgaGalTime,
    mga_glo_eph::MgaGloEph,
    mga_gps_eph::MgaGpsEph,
    mga_gps_iono::MgaGpsIono,
    mga_gps_utc::MgaGpsUtc,
    mon_comms::MonComms,
    nav_dop::NavDop,
    nav_hp_pos_ecef::NavHpPosEcef,
    nav_hp_pos_llh::NavHpPosLlh,
    nav_other::{NavEoe, NavOdo, NavVelECEF},
    nav_pl::NavPl,
    nav_pos_ecef::NavPosEcef,
    nav_pos_llh::NavPosLlh,
    nav_pvt::proto27::NavPvt,
    nav_rel_pos_ned::proto27::NavRelPosNed,
    nav_sat::NavSat,
    nav_sig::NavSig,
    nav_sol::NavSol,
    nav_status::NavStatus,
    nav_time_ls::NavTimeLs,
    nav_time_utc::NavTimeUTC,
    nav_vel_ned::NavVelNed,
    rxm_cor::RxmCor,
    rxm_rawx::RxmRawx,
    rxm_rtcm::RxmRtcm,
    rxm_sfrbx::RxmSfrbx,
    sec_sig::SecSig,
    sec_siglog::SecSiglog,
    sec_uniq_id::SecUniqId,
    tim_svin::TimSvin,
    tim_tm2::TimTm2,
    tim_tp::TimTp,
};

use crate::{ParserError, UbxPacketMeta, UbxUnknownPacket};
use ublox_derive::define_recv_packets;

define_recv_packets!(
    enum Packet {
        _ = UbxUnknownPacket<MAX_PAYLOAD_LEN>,
        AckAck,
        AckNak,
        CfgAnt,
        CfgEsfAlg,
        CfgEsfWt,
        CfgGnss,
        CfgInf,
        CfgItfm,
        CfgNav5,
        CfgOdo,
        CfgPrtI2c,
        CfgPrtSpi,
        CfgPrtUart,
        CfgTmode2,
        CfgTmode3,
        CfgTp5,
        CfgValGetResponse,
        EsfAlg,
        EsfIns,
        EsfMeas,
        EsfStatus,
        EsfRaw,
        InfError,
        InfWarning,
        InfNotice,
        InfTest,
        InfDebug,
        MonVer,
        MonGnss,
        MonHw,
        MonHw2,
        MonHw3,
        MonComms,
        MonIo,
        MonMsgpp,
        MonPatch,
        MonSpan,
        MonRf,
        MonRxr,
        MonRxbuf,
        MonTxbuf,
        MgaAck,
        MgaGpsIono,
        MgaGpsEph,
        MgaGpsUtc,
        MgaBdsEph,
        MgaBdsUtc,
        MgaGloEph,
        MgaGalEph,
        MgaGalTime,
        NavAtt,
        NavClock,
        NavCov,
        NavDop,
        NavEoe,
        NavHpPosLlh,
        NavHpPosEcef,
        NavOdo,
        NavPl,
        NavPosEcef,
        NavPvt,
        NavPosLlh,
        NavRelPosNed,
        NavSat,
        NavSig,
        NavSol,
        NavStatus,
        NavVelNed,
        NavTimeUTC,
        NavTimeLs,
        NavVelECEF,
        RxmCor,
        RxmRawx,
        RxmRtcm,
        RxmSfrbx,
        SecSig,
        SecSiglog,
        SecUniqId,
        TimSvin,
        TimTp,
        TimTm2,
    }
);
