name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  publish_derive:
    name: Publish
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Publish
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }} --allow-dirty -p ublox_derive

  publish_ublox:
    name: Publish
    needs: ['publish_derive']
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Publish
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }} --allow-dirty -p ublox
  
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/create-release@v1
      with:
        draft: true
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
